version: '3'

services:
  gitlab:
    build: gitlab
    container_name: gitlab
    hostname: gitlab
    ports:
      - "22:22"
      - "443:443"
      - "80:80"
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
    networks:
      - devops-project-network
    
  gitlab-runner:  
    build: runner
    container_name: gitlab-runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - runner-config:/etc/gitlab-runner
    networks:
      - devops-project-network
    environment:
      - CI_SERVER_URL=http://gitlab
      - RUNNER_EXECUTOR=docker
      - DOCKER_IMAGE=docker-runner
      - DOCKER_NETWORK_MODE=devops-project-network
      - DOCKER_PULL_POLICY=never

  docker-runner:
    build: builder
    image: docker-runner

  web-server:
    build: nginx
    container_name: web-server
    ports:
      - "8080:80"
    networks:
      - devops-project-network

volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
  runner-config:

networks:
  devops-project-network:
    name: devops-project-network
